### ISSUE TITLE
Why is dolphin scheduler included in this list? 

### ISSUE THREAD

**Issue by kapad** [akuity/awesome-argo#84]
> https://github.com/akuity/awesome-argo/blob/26e2992b2f5162cf7c32247fae6239bac7f048aa/README.md?plain=1#L76

Why is Apache Dolphin Scheduler in the list of projects that use Argo workflows? 

I understand that Argo workflows can be integrated into dolphin scheduler, but I don't see any support for this out-of-the-box. 

A [code search][1] for "argo" in the dolphinscheduler project does not return any results relevant to Argo workflows. Additionally, the [documentation page][2] for built-in task types for dolphinscheduler also does not list argo workflows (or even argo cd) as a built-in task. 

When I saw dolphinscheduler listed in the "Other open source projects that use Argo" section, I tried searching for a link, thinking that there is a native integration, only to later realize that this was a rabbit hole and a waste of time, because there is not native/built-in support for argo workflows in dolphin scheduler. Therefore, I think the information in the readme is confusing, and you should consider listing dolphin in another section or removing it entirely. 

[1]: https://github.com/search?q=repo%3Aapache%2Fdolphinscheduler%20argo&type=code
[2]: https://dolphinscheduler.apache.org/en-us/docs/3.2.2/introduction-to-functions_menu/task_menu 
[3]: https://github.com/akuity/awesome-argo/blob/main/README.md?plain=1#L73

**Comment by morey-tech** [comment]
Looks like it was originally added in https://github.com/akuity/awesome-argo/pull/40 with the context that "Argo CD can deploy the DolphinScheduler in a flash, and DolphinScheduler can execute Argo workflow resources" but that was [later removed](https://github.com/akuity/awesome-argo/commit/f719a27d7827e2b1bc1f867fd9465f717a97ff60#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R67).

I agree, I don't see the connection to Argo Workflows anymore.
